packages:
  - frontend
  - backend
allowBuilds:
  esbuild: true
  mongodb-client-encryption: true
minimumReleaseAgeExclude:
  - picomatch@4.0.4
  - path-to-regexp@8.4.0
  - vite@7.3.2
  - postcss@8.5.10
  - qs@6.15.2
  - '@rolldown/binding-darwin-arm64@1.2.7'
  - '@rolldown/binding-linux-ppc64-gnu@1.2.7'
